config/routes.rb
Rails.application.routes.draw do

  mount ShopifyApp::Engine, at: '/'
  mount ActionCable.server => '/cable'
  resources :products
  resources :collections do
    resources :categories do
    	resources :product_types do
    		resources :tags
    	end
    end
  end



  root :to => 'collections#index'
  post 'create_category', to: "categories#create", as: "create_collection_categories"
  get 'search', to: "collections#search", as: 'search'
  get 'home', to: "collections#home"
  get 'index', to: "collections#index"
  get 'select_change', to: "products#select_change"
  get 'navbar_select', to: "shared#navbar_select"


  namespace :api do
    get 'collections', to: "collections#index"
    get 'main', to: "javascripts#main"
  end
  #get 'tutorial', to: "shared#_tutorial"
  #get 'navbar', to: 'collections#navbar'
 #get 'products/select_change', to: "", constraints: { format: 'json' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_collection
  before_action :set_category
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]


  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = @collection.category.product_types.all
    
    @categories = @collection.categories.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = @collection.category.product_types.new
  end

  # def populate_type_select
  #   category_id = params[:category_id]
  #   @product_type = ProductTypes.find_by category_id: category_id
  #   respond_to do |format|
  #     format.json { render json: @product_type }
  #   end
  # end
  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = @collection.category.product_types.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to category_product_types_path(@category), notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to category_product_types_path(@category), notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to category_product_types_url(@category), notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_collection
      @collection = @shop.collections.find(params[:collection_id] || params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = @collection.category.find(params[:category_id] || params[:id])
    end

    def set_product_type
      @product_type = @collection.category.product_types.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:category_id, :title, :handle)
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.slim
= simple_form_for([@category, product_type]) do |f|
  - if product_type.errors.any?
    #error_explanation
      h2
        = pluralize(product_type.errors.count, "error")
        |  prohibited this product_type from being saved:
      ul
        - product_type.errors.full_messages.each do |message|
          li
            = message
  = f.input :title, label: false, :placeholder => "Title"
  - # f.input :handle
  = f.button :submit

app/views/product_types/edit.html.slim
h1
  | Editing Product Type
= render 'form', product_type: @product_type
= link_to 'Show', category_product_type_path(@category, @product_type)
|  | 
= link_to 'Back', category_product_types_path(@category)

app/views/product_types/index.html.slim
/= render 'shared/breadcrumb'
p#notice
  = notice

#category-box
  #project-list
    - if @product_types.any?
      - @product_types.each do |type|
        = link_to collection_category_product_type_path(@category, type), data:{'type-id': type.id}, class:'type' do
          .project-messages
              p.p-name = type.title

app/views/product_types/new.html.slim
.newForm
  h1
    | New Product Type
  = render 'form', product_type: @product_type

app/views/product_types/show.html.slim
p#notice
  = notice
p
  strong
    | Category:
  = @product_type.category.title
p
  strong
    | Title:
  = @product_type.title
p
  strong
    | Handle:
  = @product_type.handle
= link_to 'Tags', category_product_type_tags_path(@category, @product_type)
|  | 
= link_to 'Edit', edit_category_product_type_path(@category, @product_type)
|  | 
= link_to 'Back', category_product_types_path(@category)