config/routes.rb
Rails.application.routes.draw do

  mount ShopifyApp::Engine, at: '/'
  mount ActionCable.server => '/cable'
  resources :products
  resources :collections do
    resources :categories do
    	resources :product_types do
    		resources :tags
    	end
    end
  end



  root :to => 'collections#index'
  post 'create_category', to: "categories#create", as: "create_collection_categories"
  get 'search', to: "collections#search", as: 'search'
  get 'home', to: "collections#home"
  get 'index', to: "collections#index"
  get 'select_change', to: "products#select_change"
  get 'navbar_select', to: "shared#navbar_select"


  namespace :api do
    get 'collections', to: "collections#index"
    get 'main', to: "javascripts#main"
  end
  #get 'tutorial', to: "shared#_tutorial"
  #get 'navbar', to: 'collections#navbar'
 #get 'products/select_change', to: "", constraints: { format: 'json' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shared_controller.rb
class SharedController <ApplicationController

	def navbar_select 
		@category = Category.find_by_id(params[:category_id])
	end



end

app/views/shared/_breadcrumb.html.slim
#breadcrumb
  = link_to "Collections", index_path
  - if session[:shopify_collection_title] && session[:shopify_collection_id]
    - if ["products"].include?(params[:controller])
      |  >
      = link_to session[:shopify_collection_title] + " Products", products_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title])
    - else
      |  >
      = link_to session[:shopify_collection_title], categories_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title])
      - if @category && !@category.new_record?
        |  >
        = link_to @category.title, category_product_types_path(@category)
        - if @product_type && !@product_type.new_record?
          |  >
          = link_to @product_type.title, category_product_type_tags_path(@category, @product_type)

          - if @tag && !@tag.new_record?
            |  >
            = link_to @tag.title, category_product_type_tag_path(@category, @product_type, @tag)

app/views/shared/_filters.html.slim
h1
  | hello

app/views/shared/_navbar.html.slim
- if session[:shopify_collection_title] && session[:shopify_collection_id]
  .ul_nav
    p.logo
      = link_to "Filter Fly", index_path
    .primary_nav
      label.nav_label.collection_label
        = link_to session[:shopify_collection_title], categories_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title])
      - # if ["products"].include?(params[:controller])
      - # else
      - # end
      - # if @category
      - # end
      - if !["products"].include?(params[:controller])
        - if !@category && !@product_type && !@tag
          label.nav_label.selected
            = link_to "Categories", categories_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title])
        - else
          label.nav_label
            = link_to "Categories", categories_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title])
          - if @category && @product_types && !@product_type
            label.nav_label.selected
              = link_to "Types", category_product_types_path
          - else
            - if @product_type
              label.nav_label
                = link_to "Types", category_product_types_path
              - if @product_type && @tags
                label.nav_label.selected
                  = link_to "Tags", category_product_type_tags_path
              - else

    button.product_btn
      = link_to "Products", products_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title]), {class: "product_nav"}
  label.nav_label.support
    = link_to "Support", index_path
  - # if @products
  - # end
- else

app/views/shared/_tutorial.html.slim
| hello world

app/views/shared/navbar_select.js.slim
| $("#category-nav-
= @category ?  @category.id : 'nil'
| ").addClass("bold"); //.css("font-weight", "bold"); 