config/routes.rb
Rails.application.routes.draw do

  mount ShopifyApp::Engine, at: '/'
  mount ActionCable.server => '/cable'
  resources :products
  resources :collections do
    resources :categories do
    	resources :product_types do
    		resources :tags
    	end
    end
  end



  root :to => 'collections#index'
  post 'create_category', to: "categories#create", as: "create_collection_categories"
  get 'search', to: "collections#search", as: 'search'
  get 'home', to: "collections#home"
  get 'index', to: "collections#index"
  get 'select_change', to: "products#select_change"
  get 'navbar_select', to: "shared#navbar_select"


  namespace :api do
    get 'collections', to: "collections#index"
    get 'main', to: "javascripts#main"
  end
  #get 'tutorial', to: "shared#_tutorial"
  #get 'navbar', to: 'collections#navbar'
 #get 'products/select_change', to: "", constraints: { format: 'json' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :product_type

  has_many :product_tags, :dependent => :destroy
  has_many :products, :through => :product_tags
  validates :title, presence: true

  before_save :update_handle

	def update_handle
    	self.handle = title.parameterize
  	end

  	def as_json
		{
			id: id,
			title: title,
		}
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_collection
  before_action :set_category
  before_action :set_product_type
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = @collection.category.product_type.tags.all
    @product_types = @collection.category.product_types.all
    @categories = @collection.categories.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tags = @collection.category.product_type.tags.all
    @product_types = @collection.category.product_types.all
    @categories = @collection.categories.all
  end

  # GET /tags/new
  def new
    @tag = @collection.category.product_type.tags.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = @collection.category.product_type.tags.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to category_product_type_tags_path(@category, @product_type), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to category_product_type_tags_path(@category, @product_type), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to category_product_type_tags_path(@category, @product_type), notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = @shop.collections.find(params[:collection_id] || params[:id])
    end
    def set_category
      @category = @collection.category.find(params[:category_id] || params[:id])
    end

    def set_product_type
      @product_type = @collection.category.product_types.find(params[:product_type_id] || params[:id])
    end

    def set_tag
      @tag = @collection.category.product_type.tags.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:product_type_id, :title, :handle)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= simple_form_for([@category, @product_type, tag]) do |f|
  - if tag.errors.any?
    #error_explanation
      h2
        = pluralize(tag.errors.count, "error")
        |  prohibited this tag from being saved:
      ul
        - tag.errors.full_messages.each do |message|
          li
            = message
  = f.input :title, label: false, :placeholder => "Title"
  - # f.input :handle
  = f.button :submit

app/views/tags/edit.html.slim
h1
  | Editing Tag
= render 'form', tag: @tag
= link_to 'Show', category_product_type_tag_path(@category, @product_type, @tag)
|  | 
= link_to 'Back', category_product_type_tags_path(@category, @product_type)

app/views/tags/index.html.slim
= render 'shared/breadcrumb'
p#notice
  = notice
#collection_index
  - if @tags.any?
    h1
      | Tags
    .table
      .tbl-content
        table[cellpadding="0" cellspacing="0" border="0"]
          tbody
            - @tags.each do |tag|
              tr.row
                td
                  = link_to tag.title, products_path(shopify_collection_id: session[:shopify_collection_id], shopify_collection_title: session[:shopify_collection_title])
                td
                  = link_to 'Edit', edit_category_product_type_tag_path(@category, @product_type, tag)
                td
                  = button_to 'X', category_product_type_tag_path(@category, @product_type, tag), method: :delete, data: { confirm: 'Are you sure?' }
    - - end
    button.modalBtn
      | New Tag
    #myModal.modal
      .modal-content
        span.close
          | ×
        #newTag
    - if @tags.any?
      #begin
        h2
          | Click a tag or the products button to continue.
    - else
      #begin
        h2
          | Create a tag or click the products button to continue.
      - - end

app/views/tags/new.html.slim
.newForm
  h1
    | New Tag
  = render 'form', tag: @tag

app/views/tags/show.html.slim
.page
  = render 'shared/breadcrumb'
  #collection_index
    p#notice
      = notice
    p
      strong
        | Product type:
      = @tag.product_type.title
    p
      strong
        | Title:
      = @tag.title
    p
      strong
        | Handle:
      = @tag.handle
    = link_to 'Edit', edit_category_product_type_tag_path(@category, @product_type, @tag)
    |  | 
    = link_to 'Back', category_product_type_tags_path(@category, @product_type)