config/routes.rb
Rails.application.routes.draw do

  mount ShopifyApp::Engine, at: '/'
  mount ActionCable.server => '/cable'
  resources :products
  resources :collections do
    resources :categories do
    	resources :product_types do
    		resources :tags
    	end
    end
  end



  root :to => 'collections#index'
  post 'create_category', to: "categories#create", as: "create_collection_categories"
  get 'search', to: "collections#search", as: 'search'
  get 'home', to: "collections#home"
  get 'index', to: "collections#index"
  get 'select_change', to: "products#select_change"
  get 'navbar_select', to: "shared#navbar_select"


  namespace :api do
    get 'collections', to: "collections#index"
    get 'main', to: "javascripts#main"
  end
  #get 'tutorial', to: "shared#_tutorial"
  #get 'navbar', to: 'collections#navbar'
 #get 'products/select_change', to: "", constraints: { format: 'json' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :collection
	has_many :product_types, :dependent => :destroy
	has_many :products, :dependent => :destroy
	validates :title, presence: true

	before_save :update_handle

	def update_handle
    	self.handle = title.parameterize
  	end

  	def as_json
		{
			id: id,
			title: title,
			product_types: product_types.as_json
		}
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #ApplicationController
  before_action :set_collection
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json

  def index
    Rails.logger.debug("collection_id: @collection.id")
    @categories = @collection.categories.all

    # if !@collection
    #   @categories = []
    # else
    #   @categories = @collection.categories.all
    #
    #   #Category.where(shopify_collection_id: session[:shopify_collection_id])
    # end

    @collections = Collection.all


    # Trying Nav
    #@custom_collections = ShopifyAPI::CustomCollection.find(:all, params: { limit: 10 },shopify_collection_id: session[:shopify_collection_id])
    #@smart_collections = ShopifyAPI::SmartCollection.find(:all, params: { limit: 10 }, shopify_collection_id: session[:shopify_collection_id])

  end


  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    # @category = @collection.category.new(@collection)
    @category = @collection.categories.new()
    # @category = Category.new(shopify_collection_id: session[:shopify_collection_id])
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json


  def create
    @category = @collection.categories.new(category_params)

    if @category.save
      ActionCable.server.broadcast 'categories',
        title: @category.title,
        collection_id: @category.collection_id
      head :ok
    else

    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = @collection.category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private



    # def set_collection
    #   @shop = ShopifyAPI::Shop.current

    #   @collection = ShopifyCollection.find(params[:shopify_collection_id])

    #   # @collection = .find(params[:shopify_collection_id] || params[:id])

    # end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:category_id] || params[:id])
      # @category = @collection.category.find(params[:category_id] || params[:id])
      #Category.find(params[:category_id] || params[:id])
    end

    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :handle, :shopify_collection_id, :collection_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.slim
- for category in @categories
  = link_to collection_category_product_types_path(category.id, @collection), data:{'category-id': category.id}, class:'category' do
    .project-messages
        p.p-name = category.title

app/views/categories/_form.html.slim
.new
  = simple_form_for [@collection, @category], remote: true, :method => :post, :action => "create", :url => collection_categories_path do |f|
    - if @category.errors.any?
      #error_explanation
        h2
          = pluralize(@category.errors.count, "error")
          |  prohibited this category from being saved:
        ul
          - @category.errors.full_messages.each do |message|
            li
              = message
    = f.hidden_field :collection_id
    = f.hidden_field :shopify_collection_id
    = f.input :title, label: false, :placeholder => "Title", class:"category_title"
    - # f.input :handle
    = f.button :submit, class: "category_btn"

app/views/categories/edit.html.slim
h1
  | Editing Category
= render 'form', category: @category
= link_to 'Show', @category
|  | 
= link_to 'Back', categories_path

app/views/categories/index.html.slim
/= render 'shared/breadcrumb'
p#notice
  = notice

  #conversation
    #category-box
      #project-list
        - if @collection.categories.any?
          = render partial: 'category', collection: @collection.categories
          div class="panel-body hidden" id="categories" data-conversation-id= @collection.id
        -else

          #categories.hidden

        /  - @categories.each do |category|
        /    = link_to collection_category_product_types_path(category.id, @collection), data:{'category-id': category.id}, class:'category' do
        /      .project-messages
        /          p.p-name = category.title


//- # link_to 'Product Types', category_product_types_path(category)
//- # category.handle

app/views/categories/new.html.slim
#newForm
  = render 'form'

app/views/categories/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @category.title
p
  strong
    | Handle:
  = @category.handle
= link_to 'Product Types', category_product_types_path(@category)
|  | 
= link_to 'Edit', edit_category_path(@category)
|  | 
= link_to 'Back', categories_path